/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Gloriana
 */
public class VentanaTipoCombo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTipoCombo
     */
    public VentanaTipoCombo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSeleccionarTipoCombo = new javax.swing.JLabel();
        lblComboPredeterminado = new javax.swing.JLabel();
        lblComboAlGusto = new javax.swing.JLabel();
        radioButtonCombo1 = new javax.swing.JRadioButton();
        radioButtonCombo2 = new javax.swing.JRadioButton();
        radioButtonCombo3 = new javax.swing.JRadioButton();
        radioButtonCombo4 = new javax.swing.JRadioButton();
        radioButtonCombo5 = new javax.swing.JRadioButton();
        lblSeleccionarPlatoPrincipal = new javax.swing.JLabel();
        radioButtonHamburguesa = new javax.swing.JRadioButton();
        radioButtonSandwich = new javax.swing.JRadioButton();
        radioButtonPollo = new javax.swing.JRadioButton();
        radioButtonWrap = new javax.swing.JRadioButton();
        radioButtonPizza = new javax.swing.JRadioButton();
        radioButtonHotDog = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSeleccionarTipoCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeleccionarTipoCombo.setText("Por favor seleccione el tipo de combo:");

        lblComboPredeterminado.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblComboPredeterminado.setText("Combo predeterminado:");

        lblComboAlGusto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblComboAlGusto.setText("Combo al gusto:");

        buttonGroup1.add(radioButtonCombo1);
        radioButtonCombo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonCombo1.setText("Combo 1: Hamburguesa, gaseosa, papas (2750)");
        radioButtonCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCombo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonCombo2);
        radioButtonCombo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonCombo2.setText("Combo 2: Pollo, gaseosa, papas (2550)");

        buttonGroup1.add(radioButtonCombo3);
        radioButtonCombo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonCombo3.setText("Combo 3: Hot dog, gaseosa, puré (2550)");

        buttonGroup1.add(radioButtonCombo4);
        radioButtonCombo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonCombo4.setText("Combo 4: Pizza, gaseosa (2000)");

        buttonGroup1.add(radioButtonCombo5);
        radioButtonCombo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonCombo5.setText("Combo 5: Pizza, gaseosa, ensalada, tres leches (3400)");

        lblSeleccionarPlatoPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSeleccionarPlatoPrincipal.setText("Seleccione un plato principal");

        buttonGroup1.add(radioButtonHamburguesa);
        radioButtonHamburguesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonHamburguesa.setText("Hamburguesa (1200)");

        buttonGroup1.add(radioButtonSandwich);
        radioButtonSandwich.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonSandwich.setText("Sandwich (900)");

        buttonGroup1.add(radioButtonPollo);
        radioButtonPollo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonPollo.setText("Pollo (1000)");
        radioButtonPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPolloActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonWrap);
        radioButtonWrap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonWrap.setText("Wrap (900)");

        buttonGroup1.add(radioButtonPizza);
        radioButtonPizza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonPizza.setText("Pizza (1100)");

        buttonGroup1.add(radioButtonHotDog);
        radioButtonHotDog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioButtonHotDog.setText("Hot dog (950)");

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblComboPredeterminado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblComboAlGusto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSeleccionarTipoCombo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeleccionarPlatoPrincipal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonSandwich)
                                    .addComponent(radioButtonHamburguesa)
                                    .addComponent(radioButtonPollo))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonPizza)
                            .addComponent(radioButtonWrap)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioButtonHotDog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btnSiguiente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonCombo5)
                            .addComponent(radioButtonCombo1)
                            .addComponent(radioButtonCombo2)
                            .addComponent(radioButtonCombo3)
                            .addComponent(radioButtonCombo4))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSeleccionarTipoCombo)
                .addGap(29, 29, 29)
                .addComponent(lblComboPredeterminado)
                .addGap(18, 18, 18)
                .addComponent(radioButtonCombo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCombo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCombo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCombo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButtonCombo5)
                .addGap(15, 15, 15)
                .addComponent(lblComboAlGusto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeleccionarPlatoPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonHamburguesa)
                    .addComponent(radioButtonWrap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonSandwich)
                    .addComponent(radioButtonPizza))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioButtonPollo)
                            .addComponent(radioButtonHotDog))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCombo1ActionPerformed

    private void radioButtonPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonPolloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTipoCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTipoCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTipoCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTipoCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTipoCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComboAlGusto;
    private javax.swing.JLabel lblComboPredeterminado;
    private javax.swing.JLabel lblSeleccionarPlatoPrincipal;
    private javax.swing.JLabel lblSeleccionarTipoCombo;
    private javax.swing.JRadioButton radioButtonCombo1;
    private javax.swing.JRadioButton radioButtonCombo2;
    private javax.swing.JRadioButton radioButtonCombo3;
    private javax.swing.JRadioButton radioButtonCombo4;
    private javax.swing.JRadioButton radioButtonCombo5;
    private javax.swing.JRadioButton radioButtonHamburguesa;
    private javax.swing.JRadioButton radioButtonHotDog;
    private javax.swing.JRadioButton radioButtonPizza;
    private javax.swing.JRadioButton radioButtonPollo;
    private javax.swing.JRadioButton radioButtonSandwich;
    private javax.swing.JRadioButton radioButtonWrap;
    // End of variables declaration//GEN-END:variables
}
